services:
  httpbin:
    image: mccutchen/go-httpbin:v2.5.0
    environment:
      - MAX_BODY_SIZE=15728640 # 15 MiB
    ports:
      - 8081:8080

  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      - chown -R 101:101 /etc/envoy/logs
    volumes:
      - ./logs:/etc/envoy/logs:rw
      
  envoy:
    depends_on:
      - httpbin
    image: envoyproxy/envoy:contrib-dev
    command:
      - -c
      - /etc/envoy/envoy.yaml
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /etc/envoy/logs/envoy.log
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../plugin.so:/etc/envoy/plugin.so
      - ./logs:/etc/envoy/logs:rw
    ports:
      - 10000:10000
      - 9999:9999
    environment:
      - GODEBUG=cgocheck=0