services:
  httpbin:
    image: mccutchen/go-httpbin:v2.5.0
    environment:
      - MAX_BODY_SIZE=15728640 # 15 MiB
    ports:
      - 8081:8080

  envoy:
    depends_on:
      - httpbin
    image: envoyproxy/envoy:contrib-dev
    command:
      - -c
      - /etc/envoy/envoy.yaml
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../access.log:/etc/envoy/access.log
      - ../plugin.so:/etc/envoy/plugin.so
      - ../plugin/rules:/etc/envoy/rules
    ports:
      - 10000:10000
      - 9999:9999
    environment:
      - GODEBUG=cgocheck=0