# Copyright © 2023 Axkea, spacewander
# Copyright © 2025 United Security Providers AG, Switzerland
# SPDX-License-Identifier: Apache-2.0
---
services:
  httpbin:
    image: mccutchen/go-httpbin:2.18.1
  envoy:
    depends_on:
      - httpbin
    image: envoyproxy/envoy:contrib-dev
    command:
      - -c
      - /etc/envoy/envoy.yaml
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../coraza-waf.so:/etc/envoy/coraza-waf.so
    ports:
      - 8081:8081
      - 9999:9999
    environment:
      - GODEBUG=cgocheck=0
  tests:
    depends_on:
      - envoy
    build:
      context: .
      dockerfile: ./Dockerfile.curl
