services:
  httpbin:
    image: mccutchen/go-httpbin:v2.5.0
  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      - chown -R 101:101 /etc/envoy/logs
    volumes:
      - ./logs:/etc/envoy/logs:rw

  envoy:
    depends_on:
      - chown
      - httpbin
    image: envoyproxy/envoy:contrib-dev
    command:
      - -c
      - /etc/envoy/envoy.yaml
      - --log-path
      - /etc/envoy/logs/envoy.log
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../access.log:/etc/envoy/access.log
      - ../plugin.so:/etc/envoy/plugin.so
      - ../plugin/rules:/etc/envoy/rules
      - ./logs:/etc/envoy/logs:rw
    ports:
      - 8090:8090
    environment:
      - GODEBUG=cgocheck=0

  goFilter-logs:
    depends_on:
      - envoy
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - tail -c +0 -f /etc/envoy/logs/envoy.log | grep --line-buffered  "info" > /etc/envoy/logs/ftw.log
    volumes:
      - ./logs:/etc/envoy/logs:rw

  ftw:
    depends_on:
      - goFilter-logs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - FTW_CLOUDMODE
      - FTW_INCLUDE
    volumes:
      - ./logs:/etc/envoy/logs:ro

  ftw-memstats:
    depends_on:
      - ftw
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - "tail -c +0 -f /etc/envoy/logs/envoy.log | grep 'Sys: '"
    volumes:
      - ./logs:/etc/envoy/logs:ro